/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void demoRunsEndToEnd() {
        // Smoke test: bootstraps Hibernate + H2, seeds data, and runs every example query.
        assertDoesNotThrow(() -> App.main(new String[] {}));
    }
}
